apiVersion: v1
kind: Service
metadata:
  name: layer5adapterservice
  namespace: istio-system
  labels:
    app: layer5adapter
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 49494
    targetPort: 49494
  selector:
    app: layer5adapter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer5adapter
  namespace: istio-system
  labels:
    app: layer5adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer5adapter
  template:
    metadata:
      labels:
        app: layer5adapter
      annotations:
        # sidecar.istio.io/inject: "false" # commenting for mTLS
        sidecar.istio.io/inject: "true"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: layer5adapter
        image: layer5/layer5-istio-adapter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 49494